export const TITLE_FILTER = "TITLE_FILTER"
export const LOCATION_FILTER = "LOCATION_FILTER"
export const FULLTIME_FILTER = "FULLTIME_FILTER"

export const SINGLE_JOB_FETCH = " SINGLE_JOB_FETCH"

export const START_PLURAL_JOBS_FETCH = "START_PLURAL_JOBS_FETCH"
export const PLURAL_JOBS_FETCH = "PLURAL_JOBS_FETCH"
export const PLURAL_JOBS_FETCH_FAILURE = "PLURAL_JOBS_FETCH_FAILURE"

export const LOADING = "LOADING"
